package ir.ariana.ir.enums;

public enum Grade {
    ASSOCIATE,
    BACHELORS,
    DISCONTINUOUS_BACHELORS,
    MASTERS,
    DISCONTINUOUS_MASTERS,
    A_PROFESSIONAL_DOCTOR,
    CONTINUOUS_PHD,
    DISCONTINUOUS_SPECIALIZED_DOCTORATE
}
