package ir.ariana.ir.enums;

public enum Grade {
    ASSOCIATE_DEGREE,
    BACHELORS_DEGREE,
    DISCONTINUOUS_BACHELORS_DEGREE,
    MASTERS,
    DISCONTINUOUS_MASTERS_DEGREE,
    A_PROFESSIONAL_DOCTOR,
    CONTINUOUS_PHD,
    DISCONTINUOUS_SPECIALIZED_DOCTORATE
}
